project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - partidos.qmd

lang: es

website:
  title: "Planómetro 2026"
  site-url: "https://noamlv.github.io/PlanesPeru26/"
  navbar:
    title: false
    collapse-below: lg
    right:
      - text: Inicio
        href: "index.html"
      - text: Propuestas
        href: "index.html#panorama"
      - text: Coincidencias
        href: "index.html#similitud"
      - text: Factibilidad
        href: "index.html#concrecion"
      - text: Métodos
        href: "index.html#metodos"
      - text: Planes
        href: "partidos.html"
      - text: Contacto
        href: "index.html#contacto"

format:
  html:
    theme: default
    toc: false
    smooth-scroll: true
    css: styles.css
    include-in-header: head.html
    code-fold: false
    canonical-url: true
    open-graph: true
    twitter-card:
      card-style: summary_large_image

execute:
  echo: false
  warning: false
  message: false
